# @package _global_
defaults:
 - _self_

target: dvm
task: classification

num_classes: 286 # 286 if all views, 101 if all views2 (only front views)
weights:
live_loading: True
delete_segmentation: False
balanced_accuracy: False
eval_metric: acc
data_orig:
low_data_splits: ['']
addendum: _all_views
use_labels: False

labels_train: labels_model_all_train${addendum}.pt 
labels_val: labels_model_all_val${addendum}.pt 

data_train_imaging: train_paths${addendum}.pt
data_val_imaging: val_paths${addendum}.pt

data_train_tabular: dvm_features_train_noOH${addendum}_physical_jittered_50.csv
data_val_tabular: dvm_features_val_noOH${addendum}_physical_jittered_50.csv

field_lengths_tabular: tabular_lengths${addendum}_physical.pt


data_train_eval_tabular: dvm_features_train_noOH${addendum}_physical_jittered_50.csv
labels_train_eval_tabular: labels_model_all_train${addendum}.pt 

data_val_eval_tabular: dvm_features_val_noOH${addendum}_physical_jittered_50.csv
labels_val_eval_tabular: labels_model_all_val${addendum}.pt 

data_test_eval_tabular: dvm_features_test_noOH${addendum}_physical_jittered_50.csv 
labels_test_eval_tabular: labels_model_all_test${addendum}.pt 


data_train_eval_imaging: train_paths${addendum}.pt
labels_train_eval_imaging: labels_model_all_train${addendum}.pt

data_val_eval_imaging: val_paths${addendum}.pt
labels_val_eval_imaging: labels_model_all_val${addendum}.pt

data_test_eval_imaging: test_paths${addendum}.pt
labels_test_eval_imaging: labels_model_all_test${addendum}.pt